# Oracle Bağlantı Ayarları
spring.datasource.url=jdbc:oracle:thin:@//192.168.10.2:1521/ORCL
spring.datasource.username=stajdemo
spring.datasource.password=stajdemo
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect